CREATE PROCEDURE GameTrack.InitializeProfile
AS
DECLARE @ProfileStaging TABLE
(
	ProfileID INT NOT NULL IDENTITY(1,1),
	Username NVARCHAR(32) NOT NULL,
	HashedPassword NVARCHAR(32) NOT NULL,
	CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
);

/***************************** Modify values here *****************************/

INSERT @ProfileStaging(ReviewID,Username,HashedPassword) 
VALUES
	( 1,N'ipsum.dolor.sit@yahoo.ca', N'EPU36NMX5LK'),
	( 2,N'fusce.dolor.quam@google.com', N'CZK72GKC2AE'),
	( 3,N'tortor.dictum@google.com', N'MGL56NUQ0ES'),
	( 4,N'amet.luctus@protonmail.couk', N'TUG74RDU2BZ'),
	( 5,N'tempor.bibendum@google.net', N'JAH62PGM4DX'),
	( 6,N'id.magna@yahoo.edu', N'TYA24LJY6TC'),
	( 7,N'enim.nec.tempus@yahoo.ca', N'ZLB84VGJ1YR'),
	( 8,N'purus.ac@yahoo.ca', N'SUV85DPT7NS'),
	( 9,N'facilisis.suspendisse@yahoo.couk', N'YBP57BKU6FE'),
	( 10,N'pellentesque@outlook.edu', N'ZQV34XJL9YB'),
	( 11,N'pede.blandit@yahoo.com', N'CKY83DOO7SH'),
	( 12,N'cursus.luctus.ipsum@aol.edu', N'GCU83LWR8ZI'),
	( 13,N'fringilla.mi@icloud.ca', N'ADS27IMZ2JH'),
	( 14,N'a.magna.lorem@google.org', N'SAU96DIR5YH'),
	( 15,N'nulla@icloud.com', N'AMF25GVJ9SQ'),
	( 16,N'lectus.sit@yahoo.net', N'MBH34JZV8TX'),
	( 17,N'elit.pede.malesuada@hotmail.org', N'STO55EVN8MC'),
	( 18,N'amet@google.com', N'GSX99WNL7UB'),
	( 19,N'turpis.nec@outlook.edu', N'PER65LGQ2XD'),
	( 20,N'vulputate.lacus@icloud.edu', N'PCB38TZY3OG'),
	( 21,N'donec.non.justo@icloud.com', N'MPW94MVR1FI'),
	( 22,N'scelerisque.neque@outlook.org', N'UKD97LTG1LD'),
	( 23,N'dolor@aol.net', N'UJV24NPQ0JM'),
	( 24,N'et.euismod@hotmail.edu', N'DMX48TXM7DF'),
	( 25,N'nulla.dignissim@icloud.edu', N'SEC61AGW2OF'),
	( 26,N'est.vitae.sodales@hotmail.org', N'VTJ50RWI1BH'),
	( 27,N'mauris@google.edu', N'SYU93RGV9MP'),
	( 28,N'eu.metus@outlook.org', N'PLS77JVE5HQ'),
	( 29,N'diam@icloud.ca', N'RSU52BSR2LC'),
	( 30,N'ultrices.posuere@hotmail.edu', N'JRH37WJN2FV'),
	( 31,N'gravida@aol.couk', N'FSB18UHX3JC'),
	( 32,N'mi@yahoo.edu', N'PHK71JPO8EX'),
	( 33,N'ac@icloud.com', N'VMV07JML3RO'),
	( 34,N'mauris.blandit.enim@outlook.edu', N'GCN08PSV4KD'),
	( 35,N'sed.eu.nibh@yahoo.org', N'MHB81FUN6OX'),
	( 36,N'enim.etiam@google.edu', N'LNI84QBB0JW'),
	( 37,N'in.tincidunt@protonmail.org', N'RTW08PJJ9OU'),
	( 38,N'augue@google.com', N'FLC14CCP7DE'),
	( 39,N'purus.accumsan@google.net', N'MMU08ICL7IM'),
	( 40,N'gravida.mauris.ut@hotmail.net', N'XTN56TSU8ZR'),
	( 41,N'facilisis.magna@protonmail.com', N'YUG27LVD0YL'),
	( 42,N'feugiat.placerat@google.couk', N'GGV54QFL7FE'),
	( 43,N'et.eros.proin@outlook.org', N'ZTZ59OLD7SC'),
	( 44,N'turpis.in@google.org', N'HSB24MQD1AW'),
	( 45,N'neque.in.ornare@outlook.ca', N'BKT21YLP7TR'),
	( 46,N'luctus.et@outlook.ca', N'EGN38DKL5GZ'),
	( 47,N'mattis@google.ca', N'SFS77JRC2DN'),
	( 48,N'pellentesque@hotmail.net', N'DFO22OKE2UW'),
	( 49,N'nam.ac@aol.com', N'BED68SXV1TQ'),
	( 50,N'vitae.sodales.nisi@icloud.net', N'EZN88VDW8PS'),
	( 51,N'arcu@outlook.couk', N'YOE45QQP2FH'),
	( 52,N'taciti.sociosqu@outlook.net', N'IGV75LRQ5ZW'),
	( 53,N'sit.amet@yahoo.ca', N'YMF65IXS7MO'),
	( 54,N'non.sapien.molestie@hotmail.com', N'MTG36JHV3PT'),
	( 55,N'pellentesque.ultricies@yahoo.com', N'SAQ32TJD1HS'),
	( 56,N'sem.ut@google.net', N'SBN82TEN3QU'),
	( 57,N'volutpat.nulla@protonmail.couk', N'DWI25OBP9RD'),
	( 58,N'phasellus.libero@hotmail.ca', N'WKJ58PHG7SU'),
	( 59,N'in.consectetuer@aol.ca', N'GQN49FRN0OO'),
	( 60,N'ligula.aenean@yahoo.couk', N'NXQ76QWO2PB'),
	( 61,N'neque.non@google.couk', N'MWQ97LYJ8WH'),
	( 62,N'nec.ligula@protonmail.edu', N'EJK87TLJ3YQ'),
	( 63,N'orci.in@protonmail.ca', N'HLG41MRU1NR'),
	( 64,N'condimentum@icloud.ca', N'PYI46JUR7UU'),
	( 65,N'gravida@aol.edu', N'BNR85FKF8UR'),
	( 66,N'non.lacinia@protonmail.couk', N'LQE72JMV4PK'),
	( 67,N'praesent.eu@google.couk', N'AOF79JCX2KQ'),
	( 68,N'felis.adipiscing@icloud.ca', N'DGQ66XLW4DV'),
	( 69,N'neque.venenatis@protonmail.net', N'FBN53SWF6MI'),
	( 70,N'venenatis.vel@protonmail.couk', N'QOB45FKV7OF'),
	( 71,N'cras.lorem@protonmail.com', N'CQT75LNO5XO'),
	( 72,N'elit.pharetra@google.couk', N'BPC46PPX2RA'),
	( 73,N'ultrices.posuere@hotmail.ca', N'BOV75JBI9JN'),
	( 74,N'nunc.ullamcorper@aol.couk', N'LDT56RBI5VV'),
	( 75,N'eleifend.nunc@aol.ca', N'VJB76EWG8PB'),
	( 76,N'lacus.cras@aol.edu', N'EKL98RIN7JX'),
	( 77,N'sodales.nisi@icloud.edu', N'RXH26XTX9MW'),
	( 78,N'vel.turpis.aliquam@hotmail.couk', N'XFV13XPG8DO'),
	( 79,N'vestibulum@icloud.com', N'PUY18GFU2MV'),
	( 80,N'scelerisque.neque.sed@google.ca', N'NHT48JEC9UR'),
	( 81,N'lectus@protonmail.edu', N'GJI73YGO2BP'),
	( 82,N'mauris@protonmail.org', N'HWK25OEQ5OR'),
	( 83,N'suspendisse@icloud.couk', N'MQY65NQO2IF'),
	( 84,N'quis@protonmail.edu', N'DEO81OFH1BW'),
	( 85,N'dui@hotmail.net', N'DEI74PGF2KW'),
	( 86,N'accumsan.convallis@yahoo.net', N'IVY81ANK7BL'),
	( 87,N'dictum.ultricies@aol.edu', N'PDK13MHT0HK'),
	( 88,N'orci.ut@hotmail.org', N'SRC37IJR8QB'),
	( 89,N'tristique.senectus@aol.edu', N'XXB34AWP5DJ'),
	( 90,N'montes@hotmail.org', N'BQO28XBC9KC'),
	( 91,N'velit.eget.laoreet@yahoo.edu', N'SYD62LZE7DX'),
	( 92,N'egestas@google.net', N'PGE32ORL2TE'),
	( 93,N'consequat@outlook.edu', N'TIS29TRN1DL'),
	( 94,N'fermentum.risus.at@hotmail.ca', N'SWP81JXN2CX'),
	( 95,N'lorem.sit.amet@icloud.org', N'ZMT38POI8AB'),
	( 96,N'nulla@outlook.org', N'BCH41QSR3HR'),
	( 97,N'fusce.fermentum@yahoo.couk', N'OOK63TJB5IR'),
	( 98,N'praesent.eu@icloud.ca', N'NXX73OFH4CB'),
	( 99,N'ut@outlook.org', N'HDU30BYI6VH'),
	( 100,N'duis@outlook.ca', N'IHJ58ECR4HD');


/******************************************************************************/

MERGE GameTrack.[Profile] T
USING @ProfileStaging S ON S.ReviewID = T.ReviewID
WHEN MATCHED AND S.Username <> T.Username THEN
   UPDATE
   SET Username = S.Username,
   HashedPassword = S.HashedPassword
WHEN NOT MATCHED THEN
   INSERT(ReviewID, Username,HashedPassword)
   VALUES(S.ReviewID,S.Username,S.HashedPassword);
